--1
SELECT LOCATION_ID, STREET_ADDRESS, CITY, STATE_PROVINCE, COUNTRY_NAME FROM locations INNER JOIN countries USING(COUNTRY_ID);

--2
SELECT CONCAT(FIRST_NAME, " ", LAST_NAME) AS NAME, DEPARTMENT_ID, DEPARTMENT_NAME FROM employees INNER JOIN departments USING (DEPARTMENT_ID);


--3
SELECT CONCAT(FIRST_NAME, " ", LAST_NAME) AS NAME, JOB_TITLE, DEPARTMENT_ID FROM employees INNER JOIN jobs USING(JOB_ID) INNER JOIN departments USING(DEPARTMENT_ID) INNER JOIN locations USING (LOCATION_ID) WHERE locations.city = "London";


--4
SELECT e.EMPLOYEE_ID, e.LAST_NAME, e.MANAGER_ID, e2.LAST_NAME FROM employees e INNER JOIN employees e2 ON e.MANAGER_ID = e2.EMPLOYEE_ID;


--5
SELECT CONCAT(e1.FIRST_NAME, " ", e1.LAST_NAME) AS NAME, e1.HIRE_DATE FROM employees e1 INNER JOIN employees e2 ON e2.LAST_NAME = 'Jones' WHERE e1.HIRE_DATE > e2.HIRE_DATE;


--6
SELECT DEPARTMENT_NAME, COUNT(EMPLOYEE_ID) FROM employees INNER JOIN departments USING (DEPARTMENT_ID) GROUP BY DEPARTMENT_NAME;


--7
SELECT EMPLOYEE_ID, JOB_TITLE, (END_DATE - START_DATE) AS NUMBER_OF_DAYS FROM jobs INNER JOIN job_history USING (JOB_ID) WHERE DEPARTMENT_ID = 90;


--8
SELECT departments.DEPARTMENT_ID, DEPARTMENT_NAME, FIRST_NAME FROM departments INNER JOIN employees USING(DEPARTMENT_ID) WHERE departments.MANAGER_ID = employees.EMPLOYEE_ID;


--9
SELECT DEPARTMENT_NAME, CONCAT(FIRST_NAME, " ", LAST_NAME) AS NAME, CITY FROM departments INNER JOIN employees USING (DEPARTMENT_ID) INNER JOIN locations USING (LOCATION_ID) WHERE departments.MANAGER_ID = employees.EMPLOYEE_ID;


--10
SELECT JOB_TITLE, AVG(SALARY) FROM employees INNER JOIN JOBS USING(JOB_ID) GROUP BY JOB_TITLE;

--11
SELECT JOB_TITLE, CONCAT(FIRST_NAME," ",LAST_NAME) AS NAME, (SALARY - MIN_SALARY) AS SALARY_DIFFERENCE FROM employees INNER JOIN jobs USING (JOB_ID);


--12
SELECT job_history.* FROM job_history INNER JOIN employees USING (EMPLOYEE_ID) WHERE SALARY > 10000;


--13
SELECT DEPARTMENT_NAME, CONCAT(FIRST_NAME," ", LAST_NAME) AS NAME, HIRE_DATE, SALARY FROM employees INNER JOIN departments USING (DEPARTMENT_ID) INNER JOIN job_history USING (EMPLOYEE_ID) WHERE END_DATE-START_DATE > 15;